{application,couch,
             [{description,"Apache CouchDB"},
              {vsn,"0.8.1-communitivity"},
              {modules,[couch_btree,
                        cjson,
                        couch_db,
                        couch_doc,
                        couch_query_servers,
                        couch_file,
                        couch_server,
                        couch_server_sup,
                        couch_stream,
                        couch_key_tree,
                        couch_view,
                        couch_util,
                        couch_httpd,
                        couch_event_sup,
                        couch_db_update_notifier,
                        couch_ft_query,
                        couch_log,
                        couch_rep]},
              {registered,[couch_server,
                           couch_server_sup,
                           couch_view,
                           couch_query_servers,
                           couch_ft_query]},
              {applications,[kernel,stdlib,crypto,inets,mochiweb]},
              {env, [
                        {{"Couch", "ConsoleStartupMsg"}, "Apache CouchDB is starting."},
                        {{"Couch", "DbRootDir"}, "/usr/local/var/lib/couchdb"},
                        {{"Couch", "Port"}, 5984},
                        {{"Couch", "BindAddress"}, "127.0.0.1"},
                        {{"Couch", "DocumentRoot"}, "/usr/local/share/couchdb/www"},
                        {{"Couch", "LogFile"}, "./couch.log"},
                        {{"Couch", "UtilDriverDir"}, "/usr/local/lib/couchdb/erlang/lib/couch-0.8.1-incubating/priv/lib"},
                        {{"Couch", "LogLevel"}, "info"},
                        {{"Couch Query Servers", "javascript"}, ["/usr/local/bin/couchjs","/usr/local/share/couchdb/server/main.js"]}
                ]}
	]}.
